export const SET_NORMAL_PLAYER_SHOW = 'SET_NORMAL_PLAYER_SHOW'
export const SET_MINI_PLAYER_SHOW = 'SET_MINI_PLAYER_SHOW'
export const SET_MUSIC_PLAYING = 'SET_MUSIC_PLAYING'
export const SET_PLAY_MODE_TYPE = 'SET_PLAY_MODE_TYPE'
